controllers/DefaultController.php
<?php

class DefaultController extends AdminController
{
	/**
	 * Displays a list of all models.
	 */
	public function actionIndex()
	{
		$this->render('index',array(
			'title'=>Yii::t('YcmModule.ycm','Administration'),
			'models'=>$this->module->modelsList,
		));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if ($error=Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest) {
				echo $error['message'];
			} else {
				$this->render('error', $error);
			}
		}
	}

	/**
	 * Displays the login page.
	 */
	public function actionLogin()
	{
		$model=Yii::createComponent('LoginForm');
		if (isset($_POST['LoginForm'])) {
			$model->attributes=$_POST['LoginForm'];
			if ($model->validate() && $model->login()) {
				$this->redirect(Yii::app()->createUrl($this->module->name));
			}
		}
		$this->render('login',array('model'=>$model,'title'=>Yii::t('YcmModule.ycm','Login')));
	}

	/**
	 * Logs out the current user and redirects to home page.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout(false);
		$this->redirect(Yii::app()->createUrl($this->module->name));
	}
}

controllers/ModelController.php
<?php

class ModelController extends AdminController
{
	/**
	 * @var string Default action name
	 */
	public $defaultAction = 'list';

	/**
	 * Redactor image upload.
	 *
	 * @param string $name Model name
	 * @param string $attr Model attribute
	 * @throws CHttpException
	 */
	public function actionRedactorImageUpload($name,$attr)
	{
		$name=(string)$name;
		$attribute=(string)$attr;

		// Make Yii think this is a AJAX request.
		$_SERVER['HTTP_X_REQUESTED_WITH']='XMLHttpRequest';

		$file=CUploadedFile::getInstanceByName('file');
		if ($file instanceof CUploadedFile) {
			if (!in_array(strtolower($file->getExtensionName()),array('gif','png','jpg','jpeg'))) {
				throw new CHttpException(500,CJSON::encode(array('error'=>Yii::t(
					'YcmModule.ycm',
					'Invalid file extension "{ext}".',
					array('{ext}'=>$file->getExtensionName())
				))));
			}
			$fileName=trim(md5($attribute.time().uniqid(rand(),true))).'.'.$file->getExtensionName();
			$attributePath=$this->module->getAttributePath($name,$attribute);
			if (!is_dir($attributePath)) {
				if (!mkdir($attributePath,$this->module->permissions,true)) {
					throw new CHttpException(500,CJSON::encode(array('error'=>Yii::t(
						'YcmModule.ycm',
						'Could not create folder "{dir}". Make sure "uploads" folder is writable.',
						array('{dir}'=>$attributePath)
					))));
				}
			}
			$path=$attributePath.DIRECTORY_SEPARATOR.$fileName;
			if (file_exists($path) || !$file->saveAs($path)) {
				throw new CHttpException(500,CJSON::encode(array('error'=>Yii::t(
					'YcmModule.ycm',
					'Could not save file or file exists: "{file}".',
					array('{file}'=>$path)
				))));
			}
			$attributeUrl=$this->module->getAttributeUrl($name,$attribute,$fileName);
			$data = array(
				'filelink'=>$attributeUrl,
			);
			echo CJSON::encode($data);
			exit();
		} else {
			throw new CHttpException(500,CJSON::encode(array('error'=>Yii::t(
				'YcmModule.ycm',
				'Could not upload file.'
			))));
		}
	}

	/**
	 * Redactor image list.
	 *
	 * @param string $name Model name
	 * @param string $attr Model attribute
	 */
	public function actionRedactorImageList($name,$attr)
	{
		$name=(string)$name;
		$attribute=(string)$attr;
		$attributePath=$this->module->getAttributePath($name,$attribute);
		$files=CFileHelper::findFiles($attributePath,array('fileTypes'=>array('gif','png','jpg','jpeg')));
		$data=array();
		if ($files) {
			foreach($files as $file) {
				$fileUrl=$this->module->getAttributeUrl($name,$attribute,basename($file));
				$data[]=array(
					'thumb'=>$fileUrl,
					'image'=>$fileUrl,
				);
			}
		}
		echo CJSON::encode($data);
		exit();
	}

	/**
	 * List models.
	 *
	 * @param string $name Model name
	 */
	public function actionList($name)
	{
		$model=$this->module->loadModel($name);

		// unset default model values
		$model->unsetAttributes();

		if (isset($_GET[get_class($model)])){
			// Do not set unsafe attributes
			$params=$_GET[get_class($model)];
			foreach($params as $key => $val) {
				if (!$model->isAttributeSafe($key)){
					unset($params[$key]);
				}
			}
			$model->attributes=$params;
		}

		$this->breadcrumbs=array(
			$this->module->getAdminName($model),
		);

		$data1=array();
		if (method_exists($model,'adminSearch')) {
			$data1=$model->adminSearch();
		}

		$urlPrefix='Yii::app()->createUrl("'.$this->module->name.'/model/';
		$data2=array(
			'id'=>'objects-grid',
			'type'=>'striped bordered condensed',
			'dataProvider'=>$model->search(),
			'filter'=>$model,
			'pager'=>array(
				'class'=>'bootstrap.widgets.TbPager',
				'displayFirstAndLast'=>true,
				'firstPageLabel'=>'&lang;&lang;',
				'prevPageLabel'=>'&lang;',
				'nextPageLabel'=>'&rang;',
				'lastPageLabel'=>'&rang;&rang;',
			),
			'columns'=>array(
				array(
					'class'=>'bootstrap.widgets.TbButtonColumn',
					'updateButtonUrl'=>$urlPrefix.'update",array("name"=>"'.get_class($model).'","pk"=>$data->primaryKey))',
					'deleteButtonUrl'=>$urlPrefix.'delete",array("name"=>"'.get_class($model).'","pk"=>$data->primaryKey))',
					'viewButtonUrl'=>$urlPrefix.'view",array("name"=>"'.get_class($model).'","pk"=>$data->primaryKey))',
					'viewButtonOptions'=>array(
						'style'=>'display:none;',
					 ),
				),
			),
		);

		$data=array_merge_recursive($data1,$data2);

		if (Yii::app()->request->isAjaxRequest) {
			$this->widget('bootstrap.widgets.TbGridView',$data);
			Yii::app()->end();
		}

		$this->render('list',array(
			'title'=>$this->module->getAdminName($model),
			'model'=>$model,
			'data'=>$data,
		));
	}

	/**
	 * Create model.
	 *
	 * @param string $name Model name
	 * @throws CHttpException
	 */
	public function actionCreate($name)
	{
		$model=$this->module->loadModel($name);

		if (Yii::app()->request->isPostRequest && isset($_POST[$name])) {
			$paths=array();
			$model->attributes=$_POST[$name];

			foreach($model->tableSchema->columns as $column) {
				$attribute=$column->name;
				$widget=$this->module->getAttributeWidget($model,$attribute);
				if ($widget=='file' || $widget=='image') {
					$file=CUploadedFile::getInstance($model,$attribute);
					if ($file instanceof CUploadedFile) {
						$fileName=trim(md5($attribute.time().uniqid(rand(),true))).'.'.$file->getExtensionName();
						$attributePath=$this->module->getAttributePath($name,$attribute);
						if (!is_dir($attributePath)) {
							if (!mkdir($attributePath,$this->module->permissions,true)) {
								throw new CHttpException(500,Yii::t(
									'YcmModule.ycm',
									'Could not create folder "{dir}". Make sure "uploads" folder is writable.',
									array('{dir}'=>$attributePath)
								));
							}
						}
						$path=$attributePath.DIRECTORY_SEPARATOR.$fileName;
						if (file_exists($path) || !$file->saveAs($path)) {
							throw new CHttpException(500,Yii::t(
								'YcmModule.ycm',
								'Could not save file or file exists: "{file}".',
								array('{file}'=>$path)
							));
						}
						array_push($paths,$path);
						$model->$attribute=$fileName;
					}
				}
			}

			if ($model->save()) {
				Yii::app()->user->setFlash('success',Yii::t('YcmModule.ycm','Changes saved.'));
				$this->redirectUser($name,$model->primaryKey);
			} else if (count($paths)!=0) {
				foreach($paths as $path) {
					if (file_exists($path)) {
						@unlink($path); // Save failed - delete files.
					}
				}
			}
		}

		$title=Yii::t('YcmModule.ycm',
			'Create {name}',
			array('{name}'=>$this->module->getSingularName($model))
		);
		$this->breadcrumbs=array(
			$this->module->getAdminName($model)=>$this->createUrl('model/list',array('name'=>$name)),
			$title,
		);

		$this->render('form',array(
			'title'=>$title,
			'model'=>$model,
		));
	}
	/**
	 * Update model.
	 *
	 * @param string $name Model name
	 * @param integer $pk Primary key
	 * @throws CHttpException
	 */
	public function actionUpdate($name,$pk)
	{
		$model=$this->module->loadModel($name,$pk);

		if (Yii::app()->request->isPostRequest && isset($_POST[$name])) {
			$paths=array();
			$oldPaths=array();
			$deleteOld=array();

			// store old files to array
			foreach($model->tableSchema->columns as $column) {
				$attribute=$column->name;
				$widget=$this->module->getAttributeWidget($model,$attribute);
				if ($widget=='file' || $widget=='image') {
					$attributePath=$this->module->getAttributePath($name,$attribute);
					if (isset($model->$attribute) && !empty($model->$attribute)) {
						$path=$attributePath.DIRECTORY_SEPARATOR.$model->$attribute;
						$oldPaths[$attribute]=$path;
					}
				}
			}

			// set attributes from POST
			$model->attributes=$_POST[$name];

			foreach($model->tableSchema->columns as $column) {
				$attribute=$column->name;
				$widget=$this->module->getAttributeWidget($model,$attribute);
				if ($widget=='file' || $widget=='image') { // file or image
					$file=CUploadedFile::getInstance($model,$attribute);
					if ($file instanceof CUploadedFile) {
						$fileName=trim(md5($attribute.time().uniqid(rand(),true))).'.'.$file->getExtensionName();
						$attributePath=$this->module->getAttributePath($name,$attribute);
						if (!is_dir($attributePath)) {
							if (!mkdir($attributePath,$this->module->permissions,true)) {
								throw new CHttpException(500,Yii::t(
									'YcmModule.ycm',
									'Could not create folder "{dir}". Make sure "uploads" folder is writable.',
									array('{dir}'=>$attributePath)
								));
							}
						}
						$path=$attributePath.DIRECTORY_SEPARATOR.$fileName;
						if (file_exists($path) || !$file->saveAs($path)) {
							throw new CHttpException(500,Yii::t(
								'YcmModule.ycm',
								'Could not save file or file exists: "{file}".',
								array('{file}'=>$path)
							));
						}
						array_push($paths,$path);
						array_push($deleteOld,$attribute);
						$model->$attribute=$fileName;
					}
				}
			}

			if ($model->save()) {
				if (count($deleteOld)!=0) {
					foreach($deleteOld as $old) {
						if (isset($oldPaths[$old]) && file_exists($oldPaths[$old])) {
							@unlink($oldPaths[$old]);
						}
					}
				}
				Yii::app()->user->setFlash('success',Yii::t('YcmModule.ycm','Changes saved.'));
				$this->redirectUser($name,$model->primaryKey);
			} else if (count($paths)!=0) {
				foreach($paths as $path) {
					if (file_exists($path)) {
						@unlink($path); // Save failed - delete files.
					}
				}
			}
		}

		$title=Yii::t('YcmModule.ycm',
			'Edit {name}',
			array('{name}'=>$this->module->getSingularName($model))
		);
		$this->breadcrumbs=array(
			$this->module->getAdminName($model)=>$this->createUrl('model/list',array('name'=>$name)),
			$title,
		);

		$this->render('form',array(
			'title'=>Yii::t('YcmModule.ycm',
				'Edit {name}',
				array('{name}'=>$this->module->getSingularName($model))
			),
			'model'=>$model,
		));
	}

	/**
	 * Delete model.
	 *
	 * @param string $name Model name
	 * @param integer $pk Primary key
	 * @throws CHttpException
	 * @return void
	 */
	public function actionDelete($name,$pk)
	{

views/default/error.php
<?php
/* @var $this DefaultController */
/* @var $code string */
/* @var $message string */

$this->pageTitle=Yii::app()->name.' - '.Yii::t('YcmModule.ycm','Error');
$this->breadcrumbs=array(
	Yii::t('YcmModule.ycm','Error'),
);
?>

<h2><?php echo Yii::t('YcmModule.ycm','Error').' '.$code; ?></h2>

<div class="alert alert-error">
	<?php echo CHtml::encode($message); ?>
</div>

views/default/index.php
<?php
/* @var $this DefaultController */
/* @var $models array */

$this->pageTitle=$title;
?>

<?php $this->beginWidget('bootstrap.widgets.TbHeroUnit'); ?>
	<?php foreach($models as $model): ?>
		<div class="btn-toolbar">
			<?php
			$download=false;
			$downloadItems=array();
			if ($this->module->getDownloadExcel($model)) {
				$download=true;
				array_push($downloadItems,array(
					'label'=>Yii::t('YcmModule.ycm','Excel'),
					'url'=>$this->createUrl('model/excel',array('name'=>$model)),
				));
			}
			if ($this->module->getDownloadMsCsv($model)) {
				$download=true;
				array_push($downloadItems,array(
					'label'=>Yii::t('YcmModule.ycm','MS CSV'),
					'url'=>$this->createUrl('model/mscsv',array('name'=>$model)),
				));
			}
			if ($this->module->getDownloadCsv($model)) {
				$download=true;
				array_push($downloadItems,array(
					'label'=>Yii::t('YcmModule.ycm','CSV'),
					'url'=>$this->createUrl('model/csv',array('name'=>$model)),
				));
			}
			$this->widget('bootstrap.widgets.TbButtonGroup', array(
				'type'=>'', // '', 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
				'buttons'=>array(
					array(
						'type'=>'primary',
						'label'=>$this->module->getAdminName($model),
						'url'=>$this->createUrl('model/list',array('name'=>$model)),
					),
					array(
						'label'=>Yii::t('YcmModule.ycm','Create'),
						'url'=>$this->createUrl('model/create',array('name'=>$model)),
					),
					array(
						'label'=>Yii::t('YcmModule.ycm','List'),
						'url'=>$this->createUrl('model/list',array('name'=>$model)),
					),
				),
			));
			if ($download) {
				$this->widget('bootstrap.widgets.TbButtonGroup', array(
					'type'=>'',
					'buttons'=>array(
						array('label'=>Yii::t('YcmModule.ycm',
							'Download {name}',
							array('{name}'=>$this->module->getPluralName($model))
						)),
						array('items'=>$downloadItems),
					),
				));
			}
			?>
		</div>
	<?php endforeach; ?>
<?php $this->endWidget(); ?>

views/default/login.php
<?php
/* @var $this DefaultController */
/* @var $model LoginForm */
/* @var $form TbActiveForm */

$this->pageTitle=$title;

$form = $this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'verticalForm',
	'type'=>'inline',
	'htmlOptions'=>array('class'=>'well'),
));

echo '<p>'.Yii::t('YcmModule.ycm','Please enter your username and password.').'</p>';
echo $form->textFieldRow($model,'username',array('class'=>'input-medium','prepend'=>'<i class="icon-user"></i>')).' ';
echo $form->passwordFieldRow($model,'password',array('class'=>'input-medium','prepend'=>'<i class="icon-lock"></i>')).' ';
$this->widget('bootstrap.widgets.TbButton',array('buttonType'=>'submit','label'=>Yii::t('YcmModule.ycm','Login')));
echo '<br />'.$form->checkboxRow($model,'rememberMe');
$this->endWidget();